@startuml ComponentDiagram

cloud "Cloud" {
   package "PrintService" {
    [Python]
  }

  package "SecretService" {
    [Secret]
  }

  package "FileService" {
    folder "Folder" {
      [PrintFile]
    }
  }
  
  package "WebShop" {
    [WS_Service_N]
    [WS_Service_1]
  }

  package "PrinterManagement" {
    [PM_Service_N]
    [PM_Service_1]
  }
}

package "PrinterControlService" {
  [OctoPrint]
}

[WebShop] -- [PrintService]
[FileService] -- [PrintService]
[PrintService] -- [SecretService]
[PrintService] -- [PrinterManagement]
[PrinterManagement] -- [PrinterControlService]
@enduml