@startuml ComponentDiagram

rectangle "Cloud" {
    frame "PrintService" {
        [Python]
    }

    frame "SecretService" {
        [Secret]
    }

    frame "FileService" {
        folder "Folder" {
        [PrintFile]
        }
    }
    
    frame "WebShop" {
        [WS_Service_N]
        [WS_Service_1]
    }

    frame "PrinterManagement" {
        [PM_Service_N]
        [PM_Service_1]
    }
}

rectangle "LAN" {
    frame "PrinterControlService" {
        [OctoPrint]
    }
}

[WebShop] -down- [PrintService]
[FileService] -up- [PrintService]
[SecretService] -down- [PrintService]
[PrintService] -- [PrinterManagement]
[PrinterManagement] -down- [PrinterControlService]
@enduml