@startuml DeploymentDiagram

cloud Internet {
    node Shopify {
        component WS_Service_N
        component WS_Service_1
    }

cloud Azure {
    node KeyVault {
        component SecretService
    }

    node AppServicePlan {
        node FunctionApp {
            component PrintService
            port .
        }
    }

    rectangle Monitoring {
        node ApplicationInsights {
        }

        node LogAnalyticsWorkspace {
        }
    }

    node StorageAccount {
        component FileService
    }
}

    node Obico {
        component PM_Service_N
        component PM_Service_1
    }
}

rectangle LAN {
    node RaspberryPi {
        component OctoPrint
    }
    node Router
    node Drucker
    node Kamera
}

Shopify -left- . : TCP
KeyVault -down- . : TCP
StorageAccount -down- . : TCP
FunctionApp -down- Monitoring : TCP
ApplicationInsights -right- LogAnalyticsWorkspace : TCP
Obico -down- . : TCP
Obico -down- Router : TCP
Router -right- RaspberryPi : Ethernet
RaspberryPi -down- Drucker : Serial
RaspberryPi -down- Kamera : Serial

@enduml
