@startchen EntityRelationshipDiagram

entity Unternehmen {
}
entity Drucker {
}
entity Auftrag {
}
entity Produkt {
}
entity Bestellung {
}
entity Shop {
}
entity Kunde {
}

relationship betreibt {
}
relationship zugeordnet {
}
relationship enthalten {
}
relationship inkludiert {
}
relationship abwickeln {
}
relationship auflisten {
}
relationship aufgeben {
}
relationship registrieren {
}

aufgeben -- Kunde
aufgeben -- Bestellung
Bestellung -- inkludiert
inkludiert -- Auftrag
registrieren -- Kunde
Shop -- registrieren
Shop -- auflisten
auflisten -- Produkt
Produkt -- enthalten
enthalten -- Auftrag
zugeordnet -- Auftrag
zugeordnet -- Drucker
Shop -- abwickeln
abwickeln -- Bestellung
betreibt -- Drucker
Unternehmen -- betreibt

@endchen